<?php


 function autoload_6359f02e1ebdbbac85f1ee92760739b4($class)
{
    $classes = array(
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\CreditVerificationServiceCustom7' => __DIR__ .'/CreditVerificationServiceCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\CreditVerificationRQCustom7' => __DIR__ .'/CreditVerificationRQCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\CreditCustom7' => __DIR__ .'/CreditCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\CC_InfoCustom7' => __DIR__ .'/CC_InfoCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\PaymentCardCustom7' => __DIR__ .'/PaymentCardCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\ItinTotalFareCustom7' => __DIR__ .'/ItinTotalFareCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\TotalFareCustom7' => __DIR__ .'/TotalFareCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\DescriptiveBillingCustom7' => __DIR__ .'/DescriptiveBillingCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\FreeTextCustom7' => __DIR__ .'/FreeTextCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\AmexCustom7' => __DIR__ .'/AmexCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\AirplusCustom7' => __DIR__ .'/AirplusCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\SabreHeaderCustom7' => __DIR__ .'/SabreHeaderCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\DiagnosticResultsCustom7' => __DIR__ .'/DiagnosticResultsCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\DiagnosticsCustom7' => __DIR__ .'/DiagnosticsCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\IdentificationCustom7' => __DIR__ .'/IdentificationCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\IdentifierSystemCustom7' => __DIR__ .'/IdentifierSystemCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\MessageConditionCustom7' => __DIR__ .'/MessageConditionCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\ProblemBaseCustom7' => __DIR__ .'/ProblemBaseCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\ProblemSummaryCustom7' => __DIR__ .'/ProblemSummaryCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\ResultSummaryCustom7' => __DIR__ .'/ResultSummaryCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\SecurityCustom7' => __DIR__ .'/SecurityCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\ServiceCustom7' => __DIR__ .'/ServiceCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\TracesCustom7' => __DIR__ .'/TracesCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\TraceRecordCustom7' => __DIR__ .'/TraceRecordCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\TrackingIDCustom7' => __DIR__ .'/TrackingIDCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\CompletionCodesCustom7' => __DIR__ .'/CompletionCodesCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\DiagnosticLevelsCustom7' => __DIR__ .'/DiagnosticLevelsCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\ErrorTypeCustom7' => __DIR__ .'/ErrorTypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\TraceRoleCustom7' => __DIR__ .'/TraceRoleCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\STL_PayloadCustom7' => __DIR__ .'/STL_PayloadCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\ResultsCustom7' => __DIR__ .'/ResultsCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\ApplicationResultsCustom7' => __DIR__ .'/ApplicationResultsCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\ProblemInformationCustom7' => __DIR__ .'/ProblemInformationCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\SystemSpecificResultsCustom7' => __DIR__ .'/SystemSpecificResultsCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\HostCommandCustom7' => __DIR__ .'/HostCommandCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\CreditVerificationRSCustom7' => __DIR__ .'/CreditVerificationRSCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\SignatureTypeCustom7' => __DIR__ .'/SignatureTypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\SignatureValueTypeCustom7' => __DIR__ .'/SignatureValueTypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\SignedInfoTypeCustom7' => __DIR__ .'/SignedInfoTypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\CanonicalizationMethodTypeCustom7' => __DIR__ .'/CanonicalizationMethodTypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\SignatureMethodTypeCustom7' => __DIR__ .'/SignatureMethodTypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\ReferenceTypeCustom7' => __DIR__ .'/ReferenceTypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\TransformsTypeCustom7' => __DIR__ .'/TransformsTypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\TransformTypeCustom7' => __DIR__ .'/TransformTypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\DigestMethodTypeCustom7' => __DIR__ .'/DigestMethodTypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\KeyInfoTypeCustom7' => __DIR__ .'/KeyInfoTypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\KeyValueTypeCustom7' => __DIR__ .'/KeyValueTypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\RetrievalMethodTypeCustom7' => __DIR__ .'/RetrievalMethodTypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\X509DataTypeCustom7' => __DIR__ .'/X509DataTypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\X509IssuerSerialTypeCustom7' => __DIR__ .'/X509IssuerSerialTypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\PGPDataTypeCustom7' => __DIR__ .'/PGPDataTypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\SPKIDataTypeCustom7' => __DIR__ .'/SPKIDataTypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\ObjectTypeCustom7' => __DIR__ .'/ObjectTypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\ManifestTypeCustom7' => __DIR__ .'/ManifestTypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\SignaturePropertiesTypeCustom7' => __DIR__ .'/SignaturePropertiesTypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\SignaturePropertyTypeCustom7' => __DIR__ .'/SignaturePropertyTypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\DSAKeyValueTypeCustom7' => __DIR__ .'/DSAKeyValueTypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\RSAKeyValueTypeCustom7' => __DIR__ .'/RSAKeyValueTypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\EnvelopeCustom7' => __DIR__ .'/EnvelopeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\HeaderCustom7' => __DIR__ .'/HeaderCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\BodyCustom7' => __DIR__ .'/BodyCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\FaultCustom7' => __DIR__ .'/FaultCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\detailCustom7' => __DIR__ .'/detailCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\ManifestCustom7' => __DIR__ .'/ManifestCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\ReferenceCustom7' => __DIR__ .'/ReferenceCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\SchemaCustom7' => __DIR__ .'/SchemaCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\MessageHeaderCustom7' => __DIR__ .'/MessageHeaderCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\MessageDataCustom7' => __DIR__ .'/MessageDataCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\SyncReplyCustom7' => __DIR__ .'/SyncReplyCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\MessageOrderCustom7' => __DIR__ .'/MessageOrderCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\AckRequestedCustom7' => __DIR__ .'/AckRequestedCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\AcknowledgmentCustom7' => __DIR__ .'/AcknowledgmentCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\ErrorListCustom7' => __DIR__ .'/ErrorListCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\ErrorCustom7' => __DIR__ .'/ErrorCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\StatusResponseCustom7' => __DIR__ .'/StatusResponseCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\StatusRequestCustom7' => __DIR__ .'/StatusRequestCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\sequenceNumbertypeCustom7' => __DIR__ .'/sequenceNumbertypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\statustypeCustom7' => __DIR__ .'/statustypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\messageStatustypeCustom7' => __DIR__ .'/messageStatustypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\severitytypeCustom7' => __DIR__ .'/severitytypeCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\PartyIdCustom7' => __DIR__ .'/PartyIdCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\ToCustom7' => __DIR__ .'/ToCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\FromCustom7' => __DIR__ .'/FromCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\DescriptionCustom7' => __DIR__ .'/DescriptionCustom7.php',
        'App\GDSIntegration\Sabre\GetCreditCardApproval\WsdlClasses\UsernameTokenCustom7' => __DIR__ .'/UsernameTokenCustom7.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_6359f02e1ebdbbac85f1ee92760739b4');

// Do nothing. The rest is just leftovers from the code generation.
{
}
